[env]
TERM = "xterm-256color"
WINIT_X11_SCALE_FACTOR = "1.0"

[font]
size = 9

[font.normal]
family = "FiraCode Nerd Font"
style = "Regular"

[[keyboard.bindings]]
chars = "\u0000"
key = "Space"
mods = "Control"

[general]
import = [
  "~/dotfiles/alacritty/themes/catppuccin/catppuccin-mocha.toml"
]

[window]
dynamic_title = false
opacity = 0.8
startup_mode = "Maximized"

[window.padding]
x = 10
y = 10

[colors]
draw_bold_text_with_bright_colors = true

[keyboard]
